### ISSUE TITLE
juicer — Illegal instruction

### ISSUE THREAD

**Issue by EFalco** [vterron/lemon#63]
After we upgraded my linux box to 8 cores+32GB, of course every step is much faster.
However, lemon juicer dies when I double-click on any star. The color warning is familiar,
not lethal, not sure what it means, but nothing to do with the crash.

    tero 44> lemon juicer SDSS1210-diff6.LEMONdB 
    cannot find a color specified for photometric filter 'G', so we will use a random one instead: g. This probably means that it is a user-defined filter. If that is the case, you may want to add its color to the [colors] section of the configuration file.
    Illegal instruction

**Comment by vterron** [comment]
I had never seen this error message. From what I have found online it seems that [matplotlib is probably broken on your system](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=677026). Are you able to reproduce the error as reported [on this post on StackOverflow](http://stackoverflow.com/q/22236263/184363)?

The color warning is being emitted becase there is no color defined for the 'G' photometric filter in your `~/.juicerc` configuration file, section `[colors]`. If a curve is plotted but no color is defined for its filter in the configuration file, `juicer` prefers to use a random color rather than to stop with an error. You can always, of course, modify `.juicerc` manually to specify the color that must be used.

**Comment by EFalco** [comment]
I don't get that matplotlib.pylab error.
I updated ~/.juicerc, clean run now.
But I still get the Illegal instruction, of course.

**Comment by EFalco** [comment]
It's hard to imagine matplotlib being broken all of a sudden. It worked without any problem for
at least a month. It stopped working when I put in my entry 11 days ago, no apparent reason.

At first, I didn't get the Illegal instruction error, but if I work a little bit harder I do, see below.

Not sure why pylab isn't defined if I follow the exact thread in stackoverflow:
>>> import matplotlib.pylab
>>> matplotlib.__version__
'1.4.3'
>>> pylab.plot([1,2,3,4])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'pylab' is not defined

But it works thus:
>>> matplotlib.pylab.plot([1,2,3,4])
[<matplotlib.lines.Line2D object at 0xab26130c>]

And here's the failure again:
>>> matplotlib.pylab.show()
Illegal instruction

On another machine that runs an older matplotlib, 1.1.1, matplotlib.pylab.show() works fine.

**Comment by vterron** [comment]
The `NameError: name 'pylab' is not defined` error makes sense: the code on Stack Overflow should read `matplotlib.pylab.plot([1,2,3,4])`, as you have done, since that is the name of the imported submodule. Anyway, I cannot reproduce your error. This must almost certainly mean that something, somehow, has broken the matplotlib installation on your machine. I highly doubt the error is in any way related to our code, since there have not been any changes to the plotting code for some time.

How did you install matplotlib v.1.4.3? Maybe downgrading it to a lower version will fix it:

    pip install -I matplotlib==1.4.1

**Comment by EFalco** [comment]
Today 07 Jul 15, Ted Groner fixed the problem. It turned out that libblas is tied to the processor. After we upgraded, it was still trying to use the old one, ergo the failure. He recompiled it, and that cleared
the error.
