### ISSUE TITLE
Astronomy fails to create any file

### ISSUE THREAD

**Issue by sameerprl** [vterron/lemon#70]
>> Images will be saved to directory '1H-do/'
>> Using a local build of Astrometry.net.
>> Doing astrometry on the 5 paths given as input.
>> 0%[>                                                                        ]/home/sameer/lemon/astrometry.py:333: RuntimeWarning: zs1H0323+342_J_60s_Pos3_2.fits exceeded the timeout limit. Ignored.
  warnings.warn(msg, RuntimeWarning)
/home/sameer/lemon/astrometry.py:333: RuntimeWarning: zs1H0323+342_J_60s_Pos1_2.fits exceeded the timeout limit. Ignored.
  warnings.warn(msg, RuntimeWarning)
/home/sameer/lemon/astrometry.py:333: RuntimeWarning: zs1H0323+342_J_60s_Pos3_1.fits exceeded the timeout limit. Ignored.
  warnings.warn(msg, RuntimeWarning)
/home/sameer/lemon/astrometry.py:333: RuntimeWarning: zs1H0323+342_J_60s_Pos1_1.fits exceeded the timeout limit. Ignored.
  warnings.warn(msg, RuntimeWarning)
/home/sameer/lemon/astrometry.py:333: RuntimeWarning: zs1H0323+342_J_60s_Pos3_9.fits exceeded the timeout limit. Ignored.
  warnings.warn(msg, RuntimeWarning)
>> 100%[======================================================================>]
>> You're done ^_^

**Comment by sameerprl** [comment]
Some how disconnecting  the internet resolved the issue

**Comment by vterron** [comment]
I don't think there's any way in which the connection to the Internet may be related to this error. As the warning messages say (`exceeded the timeout limit. Ignored`), the problem is that [Astrometry.net](http://astrometry.net/) is not able to solve the image astrometrically and eventually gives up. When this happens it is usually useful to run the command with the `--ncores=1 -v` options, so that only one image is processed at a time and you can see the Astrometry.net output.
