### ISSUE TITLE
Export LEMON database using the command line

### ISSUE THREAD

**Issue by sameerprl** [vterron/lemon#74]
Hi, Is it possible to export the data from command line instead of through the GUI mode ( lemon juicer *.lemondb)

**Comment by vterron** [comment]
That functionality is not yet built into LEMON, although we intend to add it in the future. In the meantime you can use [this script that does exactly that](https://gist.github.com/vterron/0eecc47781e7482de361), and which we wrote because some workmates needed the same thing. It exports the light curves (as SVG files) of all the astronomical objects, in all the photometric filters, to an output directory.

**Comment by sameerprl** [comment]
Thanks very much

**Comment by sameerprl** [comment]
could you also add jd,instrumental mag,instrumental snr ?

**Comment by sameerprl** [comment]
done!

**Comment by vterron** [comment]
Sorry for the late reply, for the development of the pipeline is on hiatus and I currently can't devote any time to add new functionality. Could you make your version of the script public [in a Gist](http://gist.github.com/), for example, in case it may be useful for other people in the same situation as you?

**Comment by sameerprl** [comment]
Hi, was out of station, I will make it available on gist.

**Comment by sameerprl** [comment]
https://gist.github.com/sameerprl

**Comment by vterron** [comment]
Thanks a lot.
