### ISSUE TITLE
Open database without juicer

### ISSUE THREAD

**Issue by hbouy** [vterron/lemon#84]
Hi,
I have a hard time installing pygtk on my machines (Mac OS X).
Is there another (easy) way to open the .LEMONdB and extract the lightcurves?
thank you!

**Comment by vterron** [comment]
That's bad news! `juicer` is very useful as it allows to analyze  the light curves interactively. The closest thing that we have is [this script that I wrote some time ago](https://gist.github.com/vterron/0eecc47781e7482de361), in order to bulk export all the light curves from a database — would that work for you? Another option, of course, would be to generate the LEMONdB on one computer and then copy it to a different system where PyGTK is installed and therefore `juicer` is available.

**Comment by hbouy** [comment]
Dear Victor,
It is indeed a pity, and I will certainly try to get Juicer to work! It looks great. But meanwhile to go on with my analysis I need to access the light curves, so your script is perfect! 
It was still calling some Gtk module, but commenting a couple of lines (19 and 98) did the trick.
Thank you, this is very useful!
