### ISSUE TITLE
astrometry.net fiddling and failing

### ISSUE THREAD

**Issue by sengle01** [vterron/lemon#89]
Recently, it seems like astrometry.net is failing to solve a lot of my images, even though it was working great for a long time now. 

I've been fiddling around with all of the options to see what can help with the detections, but it's just not solving. Maybe the images just aren't good enough to solve, but they look perfectly fine to me. I'm not sure if anyone would actually be able to help, but I thought it was worth a shot.

[help.zip](https://github.com/vterron/lemon/files/275095/help.zip)

Also, I see that astrometry.net's image2xy program seems to have a few options of its own, such as how close two peaks (objects) are allowed to be to each other. Is this an option that can be passed along by astrometry.py?

Also also, I'm attaching a region file output from the solver (solved with downsampling at 4). When I open it up in DS9 with the image, it seems like all of the sources are offset by 10-15 pixels in the X-axis. I'm most likely missing something obvious again...

Best,
Scott

**Comment by vterron** [comment]
We don't have a way of passing options to the underlying `image2xy`, sorry. The `astrometry` command is just a convenience wrapper around Astrometry.net, because in our experience —and with our data, at least— it works perfectly most of the time out of the box, without having to adjust any of the parameters. But when that's not the case there's little leeway, as Astrometry.net uses several binaries and options but our wrapper only talks to `solve-field`.

My recommendation would be to ask in the [Astrometry.net mailing list](https://groups.google.com/forum/#!forum/astrometry), where somebody has probably seen something similar in the past and could point you in the right direction. In the meantime, also, if you need to tinker with the `image2xy` options I would suggest that you forget about LEMON's `astrometry` and do the calibration yourself, invoking the [Astrometry.net commands directly](http://astrometry.net/doc/). That's considerably more arduous, but gives you all the flexibility to experiment with different options.
