### ISSUE TITLE
Astrometry Error

### ISSUE THREAD

**Issue by aaegea** [vterron/lemon#93]
Hi all,

I am trying to use lemon but I get some errors with the first step:

	>> Doing astrometry on the 1 paths given as input.
	Traceback (most recent call last):
	  File "/Users/Alba/lemon/methods.py", line 592, in wrapper
	    return func(*args, **kwargs)
	  File "/Users/Alba/lemon/astrometry.py", line 322, in parallel_astrometry
	    output_path = astrometry_net(img.path, **kwargs)
	  File "/Users/Alba/lemon/astrometry.py", line 248, in astrometry_net
	    raise AstrometryNetError(e.returncode, e.cmd)
	AstrometryNetError: Command '['solve-field', 'AbellI_000001.fits', '--dir', '/var/folders/3r/8qpg_cmd3jx2xz9jzwt9bx6w0000gn/T/AbellI_000001_mzD7ih_astrometry.net', '--no-plots', '--new-fits', '/var/folders/3r/8qpg_cmd3jx2xz9jzwt9bx6w0000gn/T/AbellI_000001_astrometry_OXq0wR.fits', '--no-fits2fits', '--overwrite', '--radius', '1.000000']' returned non-zero exit status 255

	Exception in thread Thread-3:
	Traceback (most recent call last):
	  File "//anaconda/lib/python2.7/threading.py", line 801, in __bootstrap_inner
	    self.run()
	  File "//anaconda/lib/python2.7/threading.py", line 754, in run
	    self.__target(*self.__args, **self.__kwargs)
	  File "//anaconda/lib/python2.7/multiprocessing/pool.py", line 389, in _handle_results
	    task = get()
	TypeError: ('__init__() takes at least 3 arguments (1 given)', <class 'astrometry.AstrometryNetError'>, ())

Any suggestions for fixing that? Apparently Astrometry works well when I simply run the example in the webpage:

> solve-field --scale-low 10 demo/apod4.jpg

Thanks!!

**Comment by vterron** [comment]
What's the command you're running? Can you copy and paste it here?

It looks like the FITS image that you want to solve is `AbellI_000001.fits`. Can you upload it somewhere or share it with me? It would be useful in case I need to reproduce the problem you're seeing.

**Comment by aaegea** [comment]
I am just running:

> lemon astrometry AlbelllI_000001.fits Abell/

But I have the same error with any image. I send you the image in case you need it!

Thanks!

**Comment by vterron** [comment]
It looks like `TypeError: ('__init__() takes at least 3 arguments (1 given)', <class 'astrometry.AstrometryNetError'>, ())` is a red herring. The problem is happening when Astrometry.net's `solve-field` is executed via the `subprocess` module:

> AstrometryNetError: Command '['solve-field', 'AbellI_000001.fits', '--dir', '/var/folders/3r/8qpg_cmd3jx2xz9jzwt9bx6w0000gn/T/AbellI_000001_mzD7ih_astrometry.net', '--no-plots', '--new-fits', '/var/folders/3r/8qpg_cmd3jx2xz9jzwt9bx6w0000gn/T/AbellI_000001_astrometry_OXq0wR.fits', '--no-fits2fits', '--overwrite', '--radius', '1.000000']' returned non-zero exit status 255

What happens if you run the following command?

> solve-field AbellI_000001.fits --dir tmp-dir --no-plots --new-fits output.fits --no-fits2fits --overwrite --radius 1.000000

Note that you need to create `tmp-dir` first, of course. What I'm trying to see here is whether the command also fails if we run it ourselves, using the exact same parameters and input FITS image as when `lemon astrometry` fails.

**Comment by sengle01** [comment]
Hello,

I started getting the same error as aaegea got. So I tried running the solve-field command that you mentioned, and I first got an error:

solve-field: unrecognized option '--no-fits2fits'

So then I ran it without that option and this is what happened:

sengle01@clusty:~/RCT/TY_Sct/V/seeing$ solve-field a170621070s.fits --dir astrom --no-plots --overwrite --radius 0.2
Reading input file 1 of 1: "a170621070s.fits"...
Found an existing WCS header, will try to verify it.
Extracting sources...
simplexy: found 341 sources.
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Solving...


---------------------------------------------------------------------
You must list at least one index in the config file (/usr/local/astrometry/bin/../etc/astrometry.cfg)

See http://astrometry.net/use.html about how to get some index files.
---------------------------------------------------------------------

solve-field.c:518:run_engine engine failed.  Command that failed was:
  /usr/local/astrometry/bin/astrometry-engine astrom/a170621070s.axy
 ioutils.c:567:run_command_get_outputs Command failed: return value 255
sengle01@clusty:~/RCT/TY_Sct/V/seeing$ 



[a170621070s.zip](https://github.com/vterron/lemon/files/1114088/a170621070s.zip)


As always, any help that you could offer would be much appreciated. 


Best,
Scott

**Comment by sengle01** [comment]
Oh, wait a second. The issue is that it was looking in the wrong location (the standard one) for the configuration file, I used the --config option and it worked. As I said, it didn't recognize the --no-fits2fits option, but it worked otherwise.

For the image in question, which is attached to the previous message, here's the command and results:


solve-field a170621070s.fits --dir astrom --no-plots --overwrite --radius 0.2 --config /home/users/sengle01/astrometry_net/astrometry.cfg -u arcsecperpix -L 0.5 -H 0.7

  log-odds ratio 239.506 (1.03769e+104), 155 match, 24 conflict, 126 distractors, 233 index.
  RA,Dec = (280.552,-4.30045), pixel scale 0.571955 arcsec/pix.
  Hit/miss:   Hit/miss: +++-+c-++++++-++++-++++++++++++-+++-++++-+++--++---+-++++++++++-+--+++++c+-+-+-++--++-++-++-++c++++c
Field 1: solved with index index-4200-30.fits.
Field 1 solved: writing to file astrom/a170621070s.solved to indicate this.
Field: a170621070s.fits
Field center: (RA,Dec) = (280.552511, -4.300573) deg.
Field center: (RA H:M:S, Dec D:M:S) = (18:42:12.603, -04:18:02.064).
Field size: 9.74494 x 9.75565 arcminutes
Field rotation angle: up is 92.207 degrees E of N
Field parity: neg
Creating new FITS file "astrom/a170621070s.new"...

**Comment by sengle01** [comment]
UPDATE

I removed the nofits2fits option from lemon's astrometry command, and now IT WORKS SUCCESSFULLY.
